### ISSUE TITLE
super famicom ipl.rom

### ISSUE THREAD

**Issue by azoreseuropa** [byuu/higan#12]
I am not sure if it is the right place for help. 

I put ipl.rom in /users/myname/higan/Super Famicom/ and I created manifest and settings in Suepr Famicom folder after Icarus created mygame.sfc and it created in users/myname/emulation/Super Famicom/mygame folder/Program.rom

And Click Super Famicom then click Power and I got (no cartridge connected). Am I doing wrong ? My apologies if it is in the wrong place to put.

**Comment by byuu** [comment]
Did you connect the game to the cartridge port node at the bottom?

We really need a triage FAQ or something for using the current WIPs, they are extremely experimental and unpolished still.

**Comment by azoreseuropa** [comment]
I think we really need a FAQ and Tutorial for how to use Icarus. It is very confusion emulator. And I admit that it is not friendly emulator.

**Comment by byuu** [comment]
I know, it's in alpha status right now. higan v106 on my website should be used unless folks would like to help with the development of the new user interface. Thanks for trying it though, hopefully it'll be better soon.

**Comment by azoreseuropa** [comment]
i will wait impatiently. I go ahead with higan v106... Compiled both higan and icarus for macOS. Everything is okay. How do I load rom ? Already converted it to Program.rom. Super Famicom run and said no cartridge loaded. A little bit confused.
