### ISSUE TITLE
higan v1.06

### ISSUE THREAD

**Issue by azoreseuropa** [byuu/higan#15]
i will wait impatiently. I go ahead with higan v1.06... Compiled both higan and icarus for macOS. Everything is okay. And Icarus converted my rom. It is at /User/myname/Emulation/Megaman VII (Europe).sfc folder/Program.rom

higan and icarus are in one folder called Higan v106 and it is in Desktop. So I go to Higan--->Library--->Nintendo--->Super Famicom--->No Cartridged loaded.

**Comment by byuu** [comment]
v106 isn't really functional on macOS, I'm afraid. Best to stick to Windows and Linux there.
v106 is 17 months old, and I don't have the resources to try and backport improvements to it.

**Comment by azoreseuropa** [comment]
> v106 isn't really functional on macOS, I'm afraid. Best to stick to Windows and Linux there.
> v106 is 17 months old, and I don't have the resources to try and backport improvements to it.

I understand. Thank you. Keep up the good work.
