### ISSUE TITLE
powerpc libco implementation doesn't work on ELFv2 (64-bit little and big endian)

### ISSUE THREAD

**Issue by q66** [byuu/higan#2]
The existing implementation was written against the ELFv1 ABI on ppc64 and therefore ppc64le, which uses the ELFv2 ABI, as well as ELFv2 ABI based big endian systems will experience crashes.

For now I patched it in my distro to fall back to `sjlj.c` in those cases:

```
--- libco/libco.c
+++ libco/libco.c
@@ -9,7 +9,9 @@
     #include "amd64.c"
   #elif defined(__arm__)
     #include "arm.c"
-  #elif defined(_ARCH_PPC)
+  #elif defined(_ARCH_PPC) && (!defined(__powerpc64__) || \
+                               !defined(_CALL_ELF) || (_CALL_ELF == 1))
+    /* this implementation is only for 32-bit ppc and ELFv1 ppc64 */
     #include "ppc.c"
   #elif defined(_WIN32)
     #include "fiber.c"
```

however, in longer term this should probably be fixed properly...

i'm not good enough at ppc64 assembly to fix it

**Comment by q66** [comment]
The code could possibly be fixed. One fix is for ELFv2 itself, which should be something like

```
--- libco/ppc.c
+++ libco/ppc.c
@@ -36,7 +36,7 @@ static thread_local cothread_t co_active_handle = 0;
 
 /* whether function calls are indirect through a descriptor, or are directly to function */
 #ifndef LIBCO_PPCDESC
-  #if !_CALL_SYSV && (_CALL_AIX || _CALL_AIXDESC || LIBCO_PPC64)
+  #if !_CALL_SYSV && (_CALL_AIX || _CALL_AIXDESC || (LIBCO_PPC64 && _CALL_ELF == 1))
     #define LIBCO_PPCDESC 1
   #endif
 #endif
```

But then there's also something subtly breaking it for little endian, one part is where the entry/stack pointer is written, should be changed from

```
    t[ 8] = (uint32_t)(entry >> shift >> shift);
    t[ 9] = (uint32_t)entry;

    t[10] = (uint32_t)(sp >> shift >> shift); 
    t[11] = (uint32_t)sp;
```

to something like

```
    *(uintptr_t *)(t + 8) = entry;
    *(uintptr_t *)(t + 10) = sp;
```

However, that still doesn't fix it completely, still seems subtly broken...

**Comment by Screwtapello** [comment]
If I recall correctly, the PPC support was written for macOS and/or Linux on PowerMacs. Out of curiosity, what platform are you using libco on? Are you trying to get higan running, or just using libco for your own project?

**Comment by q66** [comment]
I'm on POWER9 (Talos 2). I'm making higan work in my Linux distro, which targets little and big endian 64-bit ELFv2 (as well as 32-bit ppc, but that should work okay OOTB).

**Comment by byuu** [comment]
That's definitely going to be a tough one. I've no access to PowerPC hardware, and this component was originally written by blargg who is no longer around for macOS before the move to Intel.

I agree with you that most expeditious choice is to revert to sjlj.c for now to avoid the crashing. I'll get that merged in today, thank you!

**Comment by q66** [comment]
Well, for big endian ELFv2 just the first thing I proposed in the `ppc.c` file should work (though I haven't tested it yet). In which case, the condition for including would be, `#if defined(_ARCH_PPC) && !defined(__LITTLE_ENDIAN__)`

**Comment by q66** [comment]
Here's a better patch:

```
--- libco/libco.c
+++ libco/libco.c
@@ -9,7 +9,7 @@
     #include "amd64.c"
   #elif defined(__arm__)
     #include "arm.c"
-  #elif defined(_ARCH_PPC)
+  #elif defined(_ARCH_PPC) && !defined(__LITTLE_ENDIAN__)
     #include "ppc.c"
   #elif defined(_WIN32)
     #include "fiber.c"
--- libco/ppc.c
+++ libco/ppc.c
@@ -36,7 +36,8 @@ static thread_local cothread_t co_active_handle = 0;
 
 /* whether function calls are indirect through a descriptor, or are directly to function */
 #ifndef LIBCO_PPCDESC
-  #if !_CALL_SYSV && (_CALL_AIX || _CALL_AIXDESC || LIBCO_PPC64)
+  #if !_CALL_SYSV && (_CALL_AIX || _CALL_AIXDESC || \
+      (LIBCO_PPC64 && (!defined(_CALL_ELF) || _CALL_ELF == 1)))
     #define LIBCO_PPCDESC 1
   #endif
 #endif
```

**Comment by q66** [comment]
I will further try to investigate whether/how the code could be fixed for little endian as well. For now, the sjlj fallback appears to work, the extra overhead of the fallback implementation should not make much of a difference considering how powerful newer ppc64 hardware is...

![](https://i.imgur.com/dKCHUam.png)

**Comment by byuu** [comment]
Thank you very much, I've committed your last patch for the next WIP updates.

I agree, ppc64le should be fast enough, especially for bsnes, for this to be a suitable workaround for now. sjlj is pretty decently fast compared to the ASM PowerPC targets, as PowerPC has a very complicated ABI to begin with. It tends to be a larger benefit for x86.

I'll leave the issue open a bit so you can review the next WIPs, and if you'd like to add anything more, then I'll close it out if you agree.

**Comment by q66** [comment]
Well, on 64-bit the modern ELFv2 ABI is significantly simpler and also faster, so it should make more of a difference there... but yeah, the workaround should be ok for now

**Comment by byuu** [comment]
Added q66's workarounds for now. In the future, it would be nice to get true ppc64le support, but it's beyond my knowledge to do so at this time. If anyone is willing to contribute, a pull request would be appreciated ^-^
