### ISSUE TITLE
[GBA] Star Wars - Episode II - Attack of the Clones (USA) glitchy intro

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#21]
using higan v106
during the intro when the words are scrolling up
in the first pic black line through the words "solar systems have declared"
in the next pic glitchy yellow line under the words "under the leadership of the"
the last pic is a glitchy line at the top of all the writing
does not happen on my gba sp
![star](https://user-images.githubusercontent.com/2696404/64057627-e1e51180-cbd1-11e9-8bb8-5bfc8a928a91.PNG)
![star1](https://user-images.githubusercontent.com/2696404/64057629-e4476b80-cbd1-11e9-961e-06a666511964.PNG)
![star2](https://user-images.githubusercontent.com/2696404/64057631-e6a9c580-cbd1-11e9-9f81-eec80f912346.PNG)

**Comment by byuu** [comment]
Migrated to board.byuu.org
