### ISSUE TITLE
[GBA] Hello Kitty Collection - Miracle Fashion Maker (Japan) black screen

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#22]
using higan v106
nothing but a black screen
works on my gba sp

**Comment by byuu** [comment]
Migrated to board.byuu.org.
And that's the last of them!
Thank you so much for reporting these bugs, I hope you don't find it disrespectful to have migrated these, but GitHub is just really not a good place for this sort of thing, having no ability to create subfolder groups.

It is going to be quite a while, if ever, that I can work on Game Boy emulation issues, I'm afraid. I support a very large number of systems and my work is quite divided. But I am hopeful to one day be able to find someone willing to work with me on higan to help with some of these systems. Most of my efforts these days go into the SNES.

Anyway, thanks again, I really appreciate it. Feel free to continue submitting bugs here or on my forum, and I'll get them merged into my bug tracking threads.
