### ISSUE TITLE
[GBA] Madden NFL 06 and Madden NFL 07 graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#24]
using higan v106
during the coin toss at the start of the game no graphics 
and during the game there is no graphics when you choose your differant plays
![madden](https://user-images.githubusercontent.com/2696404/64057965-e829bc80-cbd6-11e9-9d11-32e7f04b90e6.PNG)
![madden1](https://user-images.githubusercontent.com/2696404/64057966-e9f38000-cbd6-11e9-90e3-70bce79e6b4e.PNG)

**Comment by byuu** [comment]
Migrated to board.byuu.org
