### ISSUE TITLE
[GBA] Golden Sun (USA, Europe) graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#27]
using higan v106
on the ship the rug is covering the people
![golden](https://user-images.githubusercontent.com/2696404/64058219-98e58b00-cbda-11e9-82fa-40acb4a924ee.PNG)
here is my save if you need it
[save.zip](https://github.com/byuu/higan/files/3561996/save.zip)

**Comment by byuu** [comment]
Migrated to board.byuu.org
