### ISSUE TITLE
[GBC] Warriors of Might and Magic (USA) (En,Fr,De)corrupt graphics

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#33]
using higan v106
on the title screen and intro the graphics are corrupt
![warriors](https://user-images.githubusercontent.com/2696404/64071819-167dc980-ccb5-11e9-86a1-e56f5e985312.PNG)
![warriors1](https://user-images.githubusercontent.com/2696404/64071822-18478d00-ccb5-11e9-8934-f1ad4cb9b40d.PNG)

**Comment by benderscruffy** [comment]
using v106.208 
still happens and during gameplay there is a corrupt line
![warrior](https://user-images.githubusercontent.com/2696404/64164772-6061dd80-ce76-11e9-83a7-b3273756344d.PNG)

**Comment by byuu** [comment]
Migrated to board.byuu.org
