### ISSUE TITLE
[GBC] Ken Griffey Jr.'s Slugfest (USA) glitchy background

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#34]
using higan v106
just choose homerun derby and the background keeps on flashing
![ken](https://user-images.githubusercontent.com/2696404/64075003-1eedf880-cce5-11e9-9e00-0b868fa24451.PNG)

**Comment by benderscruffy** [comment]
still happens in v106.208
![ken](https://user-images.githubusercontent.com/2696404/64165369-8a67cf80-ce77-11e9-98c6-070171b18049.PNG)

**Comment by byuu** [comment]
Migrated to board.byuu.org
