### ISSUE TITLE
[GBC] Worms Armageddon (USA) (En,Fr,Es) white screen

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#36]
using higan v106
after selecting the quickstart game option nothing but a white screen

**Comment by benderscruffy** [comment]
still happens in v106.208
![worms](https://user-images.githubusercontent.com/2696404/64165531-ddda1d80-ce77-11e9-9eef-62370e957099.PNG)

**Comment by byuu** [comment]
Migrated to board.byuu.org
