### ISSUE TITLE
[GBC] Razor Freestyle Scooter (USA) graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#39]
using v106.208
developers screen and title screen glitchy
![razor1](https://user-images.githubusercontent.com/2696404/64166817-76719d00-ce7a-11e9-9029-8270f9d76fbc.PNG)
![razor](https://user-images.githubusercontent.com/2696404/64166821-78d3f700-ce7a-11e9-961f-8bbe1756446f.PNG)

**Comment by byuu** [comment]
Migrated to board.byuu.org
