### ISSUE TITLE
[GBC] Little Mermaid II, The - Pinball Frenzy (USA) (En,Fr,De,Es,It) (Rumble Version) graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#40]
using v106.208
nearly every single screen is glitchy
here is a couple
![little](https://user-images.githubusercontent.com/2696404/64167082-0f081d00-ce7b-11e9-84ac-aa66e3e7cd65.PNG)
![little1](https://user-images.githubusercontent.com/2696404/64167097-14fdfe00-ce7b-11e9-9717-a16dfa76a891.PNG)
![little2](https://user-images.githubusercontent.com/2696404/64167103-16c7c180-ce7b-11e9-9c35-f6c58cd04530.PNG)

**Comment by byuu** [comment]
Migrated to board.byuu.org
