### ISSUE TITLE
higan hotkeys are active when higan is not focussed

### ISSUE THREAD

**Issue by Screwtapello** [byuu/higan#48]
## Steps to reproduce:

 1. Set higan's "Toggle System Panels" hotkey to Spacebar (or anything else)
 2. Click a component in the component list at the bottom left, to let higan know it has keyboard focus
 3. Switch to a different app (like a web-browser with the GitHub "New Issue" page open)
 4. Start typing in the web-browser.

## Expected results

Text typed in the browser only affects the browser.

## Actual results

Every time I hit the spacebar while typing this bug report, higan's system panels toggle on or off.

## Notes:

If nothing has keyboard focus (say, if you pick "Video" or "Audio" from the Settings menu, and don't click anything else) then higan ignores key presses.

**Comment by byuu** [comment]
I fixed the hotkeys issue, they only trigger when the main window has focus, or you're in fullscreen exclusive mode, or you're in fullscreen exclusive mode and the video window has focus (this one took a new ruby API to implement.) They are still suppressed when the hotkeys mapping panel is open.

Hotkeys work for me when picking "video", maybe it's a Windows only issue?

**Comment by Screwtapello** [comment]
I doubt it's a Windows-only issue, since I'm not on Windows. Still, I confirm this issue is fixed!
