### ISSUE TITLE
Mac error

### ISSUE THREAD

**Issue by azoreseuropa** [byuu/higan#5]
Compiling it and I got an error -- same as bsnes. 
In file included from ../hiro/hiro.cpp:5:
In file included from ../hiro/core/core.cpp:33:
../hiro/core/color.cpp:7:8: error: cannot define or redeclare 'Color' here
      because namespace 'hiro' does not enclose namespace 'Color'
Color::Color(signed red, signed green, signed blue, signed alpha) {
~~~~~~~^
../hiro/core/color.cpp:8:12: error: use of undeclared identifier 'red'
  setColor(red, green, blue, alpha);
           ^
../hiro/core/color.cpp:8:17: error: use of undeclared identifier 'green'
  setColor(red, green, blue, alpha);
                ^
../hiro/core/color.cpp:8:24: error: use of undeclared identifier 'blue'
  setColor(red, green, blue, alpha);
                       ^
../hiro/core/color.cpp:8:30: error: use of undeclared identifier 'alpha'
  setColor(red, green, blue, alpha);
                             ^
../hiro/core/color.cpp:11:8: error: cannot define or redeclare 'operator bool'
      here because namespace 'hiro' does not enclose namespace 'Color'
Color::operator bool() const {
~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [obj/hiro-cocoa.o] Error 1

**Comment by Screwtapello** [comment]
Specifically, the same as https://github.com/byuu/bsnes/issues/3

**Comment by byuu** [comment]
This was a bug with a missing } in cocoa/viewport.cpp, it has been fixed now and you'll see it in the next commit. Thanks LIJI!
