### ISSUE TITLE
SG-1000: Bank Panic (Japan) glitchy graphics

### ISSUE THREAD

**Issue by zgoldstein420** [byuu/higan#50]
The title screen has some graphical glitching with regards to the text.
![higansg1000-1](https://user-images.githubusercontent.com/55938119/66323756-e647cd00-e8e9-11e9-9b62-02fb2ade3a1d.png)

**Comment by byuu** [comment]
Fixed it, thank you. I was missing sprite zoom. Will be in the next WIP.

![EGUjkpzVAAEjGoZ](https://user-images.githubusercontent.com/2107894/66361838-54a89000-e9bb-11e9-9fc0-4fffae25c318.png)
