### ISSUE TITLE
SG-1000 The Castle doesn't boot

### ISSUE THREAD

**Issue by zgoldstein420** [byuu/higan#52]
![higansg1000-2](https://user-images.githubusercontent.com/55938119/66362900-07d8a100-e94a-11e9-97e9-16470fcab676.png)

It gets stuck on this screen, no matter which inputs I make.

**Comment by xdanieldzd** [comment]
The Castle has 8k of extra RAM, the lack of which will cause the game to hang like in the screenshot and/or reset itself (probably depending on how the memory map is handled overall?)

(And speaking of, Othello will probably not work either, since that has 2k of extra RAM on the cartridge and will hang on a black screen without it.)

**Comment by zgoldstein420** [comment]
Apparently, higan is giving this game *too much RAM*, 32 KB to be exact.

**Comment by xdanieldzd** [comment]
Looking through higan's code, it _seems_ to treat SG-1000 cartridges as using the common Sega mapper, assuming the code in the higan/sg/cartridge directory is responsible. That mapper is as far as I'm aware only used in SMS and GG games, not SG-1000, and this is probably at least part of the reason why the game isn't working properly.

Disregard this post if my assumption is incorrect.

For what it's worth, my own emulator runs this game fine with 32 KB of cartridge RAM and its SG-1000 cartridge handling, but it hangs just like this regardless of RAM size, if it's treated as a common Sega mapper game. It's in C# and presumably also not fully accurate, but [this is how it does it right now](https://github.com/xdanieldzd/Essgee/blob/423f6eed2b729a8905c87915a0b905b299219ae1/Essgee/Emulation/Cartridges/SegaSGCartridge.cs).

**Comment by byuu** [comment]
Migrated to https://board.byuu.org/viewtopic.php?f=5&t=10
Thank you for the report.
