### ISSUE TITLE
Strange crash issue with trying gamecube controller for SNES on Higan

### ISSUE THREAD

**Issue by OmegaDarkMage** [byuu/higan#57]
Not sure what the cause is, I'm using a 3rd party driver developed by toadking to make my gamecube controller adapter work on linux and input seems to work well with all the other systems on Higan but crashes when trying on SNES. Any ideas on the cause for this strange issue? 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44561379/67626596-5bd4f800-f81b-11e9-889e-67ae233dcad2.gif)

**Comment by Screwtapello** [comment]
This is higan v106, I assume?

Does the same thing happen with the latest [nightly builds](https://cirrus-ci.com/github/byuu/higan/master)? (the UI is very different, [this tutorial](https://zork.net/~st/jottings/Getting_Started_with_higan_v106.217.html) might help).

Also, if you can run higan from a terminal, it might print some kind of helpful error message when it crashes. If you're comfortable building higan from source, it would be helpful to build it in debug mode and get a backtrace of the crash.

If you disconnect your Gamecube adapter, that prevents the crash, right?

**Comment by OmegaDarkMage** [comment]
It's the stable version (v106) that I installed from the Linux Mint software manager. Also tried running it from a terminal and got a message saying Segmentation fault (core dumped). This only happens when using the Gamecube controller Adapter. I haven't tried the nightly builds yet since I usually only use the stable versions as a rule of thumb but will consider trying the latest nightly build just to test and then report back to you.

**Comment by byuu** [comment]
I'm afraid I don't support v106 anymore. It's about two years old and the GUI has been completely replaced. I know there's no v107 yet, but I'm working on it ^-^;

That said, I don't know a solution to your issue or I would have provided it, sorry.

**Comment by OmegaDarkMage** [comment]
No worries, I can just use other controllers for the SNES for now. The Gamecube controller was just the preferred controller for me among the ones I have. Could be some issue with Linux and how it handles the gamecube controller adapter in some cases.
