### ISSUE TITLE
new Mac error

### ISSUE THREAD

**Issue by azoreseuropa** [byuu/higan#6]
In file included from ../ruby/ruby.cpp:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:48:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSGeometry.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:259:34: error: 
      missing ')' after '__attribute__'
# if __CG_HAS_COMPILER_ATTRIBUTE(noinline)
                                 ^~~~~~~~
../nall/platform.hpp:106:35: note: expanded from macro 'noinline'
  #define noinline   __attribute__((noinline))
                     ~~~~~~~~~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:19:66: note: 
      expanded from macro '__CG_HAS_COMPILER_ATTRIBUTE'
#  define __CG_HAS_COMPILER_ATTRIBUTE(attribute) __has_attribute(attribute)
                                                                 ^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:259:6: note: 
      to match this '('
# if __CG_HAS_COMPILER_ATTRIBUTE(noinline)
     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:19:65: note: 
      expanded from macro '__CG_HAS_COMPILER_ATTRIBUTE'
#  define __CG_HAS_COMPILER_ATTRIBUTE(attribute) __has_attribute(attribute)
                                                                ^
1 error generated.
make: *** [obj/ruby.o] Error 1

**Comment by MerryMage** [comment]
The below diff "fixes" this, and compilation proceeds normally thereafter.

```
diff --git a/ruby/ruby.cpp b/ruby/ruby.cpp
index ae0569e3..4d7d54ac 100755
--- a/ruby/ruby.cpp
+++ b/ruby/ruby.cpp
@@ -11,6 +11,7 @@ using namespace ruby;
   #include <X11/Xutil.h>
   #include <X11/Xatom.h>
 #elif defined(DISPLAY_QUARTZ)
+  #undef noinline
   #include <nall/macos/guard.hpp>
   #include <Cocoa/Cocoa.h>
   #include <Carbon/Carbon.h>
```

**Comment by byuu** [comment]
Awesome! Thank you MerryMage! I've added the fix and it'll be in the next push.

**Comment by azoreseuropa** [comment]
> The below diff "fixes" this, and compilation proceeds normally thereafter.
> 
> ```
> diff --git a/ruby/ruby.cpp b/ruby/ruby.cpp
> index ae0569e3..4d7d54ac 100755
> --- a/ruby/ruby.cpp
> +++ b/ruby/ruby.cpp
> @@ -11,6 +11,7 @@ using namespace ruby;
>    #include <X11/Xutil.h>
>    #include <X11/Xatom.h>
>  #elif defined(DISPLAY_QUARTZ)
> +  #undef noinline
>    #include <nall/macos/guard.hpp>
>    #include <Cocoa/Cocoa.h>
>    #include <Carbon/Carbon.h>
> ```

Thank you so much for helping!!!!
