### ISSUE TITLE
Green lines on the "overscan" in Jurassic Park (USA) (Rev 1)

### ISSUE THREAD

**Issue by obunden** [byuu/higan#61]
The lines can be seen in the latest git version of higan. They are also present in the latest git version of bsnes / official git libretro core. I disabled all cropping / overscan removal that I could find both in the standalone versions / cores and in retroarch.

Higan seems to have an extra line at the bottom compared to bsnes. There are no lines visible in snes9x libretro or the the mesen-s core, but I don't know if this is accurate or not.

Bsnes standalone:
![bsnes_standalone](https://user-images.githubusercontent.com/56209614/68840990-0bd3ad80-06c4-11ea-901c-26848ea9368e.png)

Higan standalone:
![higan_standalone](https://user-images.githubusercontent.com/56209614/68841000-0fffcb00-06c4-11ea-8eb4-5e4449e27c4c.png)

**Comment by byuu** [comment]
Does it happen with every video driver? Some drivers have bad edge clamping.

**Comment by obunden** [comment]
I get lines in the latest bsnes standalone version in all available video modes that I can see. Xvideo has lines both to the left and bottom and Xhsm / Opengl 2.0 / Opengl 3.2 has one to the left only. The thickness of the line to the left (or the placement) seems to varie a bit tho.

**Comment by obunden** [comment]
I just realized that there seems to be a a line on the right side also, but it is "connected" to the real game output so it's kinda camouflaged. If i'm not mistaken it can be seen on all video modes, but the color of the line seems to change. The previously included images can be used as examples if you zoom in a lot.

**Comment by byuu** [comment]
I fixed the left-line issue, which was an emulation core issue. The other lines are due to video drivers. We can make a new issue for that if you like, but it'll be lower priority.
