### ISSUE TITLE
[Feature Request] Libretro ports

### ISSUE THREAD

**Issue by Testsr** [byuu/higan#64]
I would like to port over some Higan implementations to libretro cores. The Wonderswan, PC Engine and Neo Geo Pocket would be good ones to port.

**Comment by byuu** [comment]
If someone wants to try and port higan's tree-view Node structure to libretro, they're more than welcome to do so. I think it's a truly extreme amount of work and will likely fail (libretro and higan are entirely different designs), but if you succeed then every core will work at once.

I may in the future create bsnes-style forks of my WonderSwan and Neo Geo Pocket emulators, but probably not any time soon.
