### ISSUE TITLE
Icarus v107 crashes while loading 7-zipped file.

### ISSUE THREAD

**Issue by Xeon3D** [byuu/higan#65]
While importing my selection of 7zipped GBA games, icarus kept crashing after (or so it seemed) the first one. After ignoring the first game and selecting the rest, it kept crashing and after some testing it does crash with every 7zipped file from my GBA games directory that I've tried.

Steps to reproduce:
- Open Icarus 107
- Choose to import some 7-zipped GBA rom files (mine are renamed to work with retroarch)

Expected result: Game imported into the database
Actual result: Program crashes.

**Comment by byuu** [comment]
7zip isn't supported by icarus, sorry. Maybe in the future but probably not ... it's too much code. I put it into bsnes to be user-friendly, but I try to keep higan/icarus lean.

**Comment by byuu** [comment]
I at least found the source of the crash, trying to detect save RAM type when no save RAM is found (which would happen when icarus failed to extract a 7zip archive.)

Hopefully a failed import is better than a crash at least.
