### ISSUE TITLE
Famicon Mirroring Error

### ISSUE THREAD

**Issue by hugoarpin** [byuu/higan#67]
On the latest build I'm getting mirroring errors for the famicom on some games. For example Super Mario Bros (USA), which is a simple nes-nrom board. If I invert the value of settings.mirror inside higan/fc/cartridge/board/nes-nrom.cpp it fixes the problem.

What drives me crazy is that looking at readCHR and writeCHR, the mirroring algorithm seems to be accurate and it does produces the values I would expect (for vertical mirroring: addr & 0x07ff).

As far as I can tell this only affects the background tiles (nametables), the sprites seem to be ok.

What am I missing?

**Comment by byuu** [comment]
Very strange, is it only with NROM games or all games that use that setting?

**Comment by hugoarpin** [comment]
I can reproduce with Castlevania (USA) which is a UxROM with vertical mirroring.

**Comment by byuu** [comment]
Sounds like I have my work cut out for me then in reviewing all of the mappers. Strange that this happened recently-ish, I didn't notice. Thanks for the report, I'll get it fixed.

**Comment by hugoarpin** [comment]
Ok so I tried Ice Climber which is another NROM (mapper 0) but with horizontal mirroring instead of vertical, and it works fine. So my "fix" of inverting the mirror value in that case causes a bug. That strongly suggests that the mirroring algorithm is not the issue.

Excitebike another NROM but with vertical mirroring has the bug, just like Super Mario Bros.
As mentioned previously, Castlevania has the bug and it is a UxROM with vertical mirroring.

So the problem seems to only be (but I'm not sure) with certain boards with vertical mirroring (games that scroll horizontally) and strangely enough inverting the CIRAM mirroring in those cases fixes the bug. The problem is maybe in the PPU rendering with X scroll position but I'm not sure.

Other games with more complicated mappers seem to work fine, like Mega Man 2 (SXROM MMC1) and Toki (TLROM MMC3).

**Comment by byuu** [comment]
I fixed it, thank you.

I moved to manifest format to "game/board/mirror/mode", but the NES boards were checking "board/mirror/mode", so the result was always horizontal mode.

It'll work in v107.4+ correctly.
