### ISSUE TITLE
can't configure Start button for Sega Master Drive

### ISSUE THREAD

**Issue by odigity** [byuu/higan#72]
I'm running Higan 106 on Ubuntu 18.04.  I just tried playing some Sega Master Drive games for the first time, but was unable to start them because the Input Settings window didn't let me configure an input for the Start button.  (see screenshot)

![Screenshot from 2020-01-29 21-19-55](https://user-images.githubusercontent.com/155179/73422343-88e2ec00-42dd-11ea-89a8-c18ad6e65a7b.png)

**Comment by Screwtapello** [comment]
If you look at [a picture of the Master System controller](https://commons.wikimedia.org/wiki/File:Sega-Master-System-Controllers.jpg) you'll see that "Start" is actually just an additional label for the "1" button.

**Comment by MiltosKoutsokeras** [comment]
The fact the problem is on the Sega Master Drive should make people suspicious... :)
