### ISSUE TITLE
Direct command line launch with ROM & -fullscreen not doing anything (Linux)

### ISSUE THREAD

**Issue by ewmailing** [byuu/higan#73]
I am trying to invoke higan through the command line, with the -fullscreen option and specifying a ROM path, with the hope/expectation that higan will directly start running the ROM in fullscreen and bypass the GTK UI. (From the docs and other old posts around the internet, it seems like this should work.) My ultimate goal is to use some kind of gamepad-friendly front-end to directly launch higan to run a selected ROM.

But so far in all my attempts, all my command line options seem to be ignored, and I always get the higan GTK UI, and it has not powered on the ROM. If I drill down to the emulator (I currently only have Super Famicom setup), I see that my ROM is specified as the cartridge but I don't know if it is because it remembered the last time I was in the GUI or picked it from the CLI. Basically, higan acts exactly the same way as if I had invoked it with no command line parameters at all. -fullscreen seems to do absolutely nothing.

I've tried https://byuu.org/download/higan/higan_v107-source.zip which is what you link to on your main page. And I tried building directly from git. I get the same results in both cases.

Thank you

**Comment by byuu** [comment]
It's --fullscreen. Outside of that, not sure.

**Comment by RokkumanX** [comment]
I was about to create a new issue about the same thing, how on earth do you use command line arguments with latest higan releases to boot games? I'm trying to boot Super Famicom games with higan v107.15 using command line but it's impossible.

I'm on Windows 10 and I have been using higan v106r52 for quite a while and it is a piece of cake to launch games with command line arguments ("path to higan" "path to game")

The same commands only opens higans interface in v107.15 and does not start a game at all.

Is there something I have missed?

**Comment by ewmailing** [comment]
You are not missing anything. This is the behavior I'm seeing. This is what I meant be "Direct command line launch" "not doing anything", and also "Basically, higan acts exactly the same way as if I had invoked it with no command line parameters at all."

**Comment by byuu** [comment]
> how on earth do you use command line arguments with latest higan releases to boot games?

You don't, it's not supported yet.
