### ISSUE TITLE
More controller ports for Super Famicom emulation

### ISSUE THREAD

**Issue by retanoid** [byuu/higan#74]
It would be great if more than two controller ports were supported for Super Famicom. ZSNES supports more than two, but unfortunately, it's unmaintained and much less stable than Higan. And there are ROMs that can use more than two controller ports.

**Comment by Screwtapello** [comment]
higan *does* support more than two controller ports. In the place where you configure what controller is plugged in, one of the "controllers" you can attach is a Super Multitap, which adds four more controller ports. You know, [something like this](https://commons.wikimedia.org/wiki/File:Super_Nintendo_MultiTap.jpg).

**Comment by byuu** [comment]
Yeah, higan is extremely literal and lets you do silly things like daisy-chain multitaps (it won't actually work, but you can do it and it'll not work just like it wouldn't work on a real SNES), or plug in light guns to the multitaps (again, won't really work, but it will -sort- of work, just like it would on a real SNES.)

bsnes is likely the better option to use for convenience for now. The upcoming byuu may one day be a full replacement for higan, but I don't intend to ship multi-player support on the first release of it.
