### ISSUE TITLE
[Mega Drive] Can't lock-on Sonic & Knuckles with Sonic the Hedgehog 2

### ISSUE THREAD

**Issue by jhlkek** [byuu/higan#79]
When I select Sonic & Knuckles in the first cartridge slot and Sonic the Hedgehog 2 in the second cartridge slot, higan shows a black screen instead of "Knuckles the Echidna in Sonic the Hedgehog 2". However, locking Sonic & Knuckles with Sonic 3 gives Sonic 3 & Knuckles and locking it with Sonic 1 gives the "No way" screen as expected.

**Comment by mlindstr** [comment]
It only works if you have the 256 KiB UPMEM patch ROM available. See e.g. https://plutiedev.com/lockon#sonic-2 for details.

**Comment by jhlkek** [comment]
Oh, my mistake. Thanks for the help.
